# Generated by Django 4.0.6 on 2022-08-16 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_delete_cartinfo_delete_delivery_delete_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(max_length=20, verbose_name='title'),
        ),
    ]
