# Generated by Django 4.0.6 on 2022-08-21 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_alter_categories_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='total_purchased',
            field=models.IntegerField(verbose_name='total purchased'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='text_content',
            field=models.CharField(max_length=20, verbose_name='Текст вашего отзыва'),
        ),
    ]
