# Generated by Django 4.0.6 on 2022-09-04 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0002_remove_products_currency_char_products_contacts_and_more'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.products',
                                    verbose_name='product'),
        ),
    ]
