# Generated by Django 4.0.6 on 2022-08-21 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.delivery',
                                               verbose_name='Доставка')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.payment',
                                              verbose_name='Оплата')),
            ],
        ),
    ]
